#! /bin/bash 

if [ $1 == 4 ]
then
	make test7_step4files TESTARGS=$2
if[ $1 == 5 ]
then
	make test7_step5files TESTARGS=$2
if [ $1 == 6 ]
then
	make test7 TESTARGS=$2
fi

#make test3 TESTARGS='test1'
#make test3 TESTARGS='test5'
#make test3 TESTARGS='test6'
#make test3 TESTARGS='test7'
#make test3 TESTARGS='test8'
#make test3 TESTARGS='test9'

#make test3 TESTARGS='test11'
#make test3 TESTARGS='test14'
#make test3 TESTARGS='test13'

#make test3 TESTARGS='test16'

#make test3 TESTARGS='test18'

#make test3 TESTARGS='test19'

#make test3 TESTARGS='test20'
