#! /bin/bash
#make compiler

make test5 TESTARGS=$1 

#if [ $1 == 1 ]
#then
#	make test5 TESTARGS='step4_testcase'
#else
#	make test5 TESTARGS='test_if'
#fi


#make test3 TESTARGS='test1'
#make test3 TESTARGS='test5'
#make test3 TESTARGS='test6'
#make test3 TESTARGS='test7'
#make test3 TESTARGS='test8'
#make test3 TESTARGS='test9'

#make test3 TESTARGS='test11'
#make test3 TESTARGS='test14'
#make test3 TESTARGS='test13'

#make test3 TESTARGS='test16'

#make test3 TESTARGS='test18'

#make test3 TESTARGS='test19'

#make test3 TESTARGS='test20'
